--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-24-2014   
--------------------------------------------------------
DROP TABLE "CRISTO"."CLIENTE_TEL" cascade constraints;
DROP TABLE "CRISTO"."HABITANTES" cascade constraints;
DROP TABLE "CRISTO"."SDA_AGREGADORES" cascade constraints;
DROP TABLE "CRISTO"."SDA_LOG_DEPURACION" cascade constraints;
DROP TABLE "CRISTO"."SDA_METODOS" cascade constraints;
DROP TABLE "CRISTO"."SDA_PAISES" cascade constraints;
DROP TABLE "CRISTO"."SDA_PARAMETROS" cascade constraints;
DROP TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" cascade constraints;
DROP TABLE "CRISTO"."SDA_RESPUESTAS" cascade constraints;
DROP TABLE "CRISTO"."SDA_USUARIO_SISTEMA" cascade constraints;
DROP SEQUENCE "CRISTO"."SQ_SDA_AGREGADORES";
DROP SEQUENCE "CRISTO"."SQ_SDA_LOG_DEPURACION";
DROP SEQUENCE "CRISTO"."SQ_SDA_METODOS";
DROP SEQUENCE "CRISTO"."SQ_SDA_PAIS";
DROP SEQUENCE "CRISTO"."SQ_SDA_PARAMETROS";
DROP SEQUENCE "CRISTO"."SQ_SDA_PARAMETROS_SISTEMA";
DROP SEQUENCE "CRISTO"."SQ_SDA_RESPUESTAS";
DROP SEQUENCE "CRISTO"."SQ_SDA_USUARIO_SISTEMA";
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_AGREGADORES
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_AGREGADORES"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 101 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_LOG_DEPURACION
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_LOG_DEPURACION"  MINVALUE 1 MAXVALUE 100000000 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_METODOS
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_METODOS"  MINVALUE 1 MAXVALUE 50000 INCREMENT BY 1 START WITH 1001 CACHE 1000 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_PAIS
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_PAIS"  MINVALUE 1 MAXVALUE 300 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_PARAMETROS
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_PARAMETROS"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1001 CACHE 1000 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_PARAMETROS_SISTEMA
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_PARAMETROS_SISTEMA"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 1 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_RESPUESTAS
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_RESPUESTAS"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 1001 CACHE 1000 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_SDA_USUARIO_SISTEMA
--------------------------------------------------------

   CREATE SEQUENCE  "CRISTO"."SQ_SDA_USUARIO_SISTEMA"  MINVALUE 2 MAXVALUE 10000 INCREMENT BY 1 START WITH 2 CACHE 100 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENTE_TEL
--------------------------------------------------------

  CREATE TABLE "CRISTO"."CLIENTE_TEL" 
   (	"ID" NUMBER, 
	"NUMERO" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HABITANTES
--------------------------------------------------------

  CREATE TABLE "CRISTO"."HABITANTES" 
   (	"HABITANTES_ID" VARCHAR2(10 BYTE), 
	"NOMBRES" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(100 BYTE), 
	"CARGO" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SDA_AGREGADORES
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_AGREGADORES" 
   (	"ID" NUMBER, 
	"NOMBRE_AGREGADOR" VARCHAR2(255 BYTE), 
	"ESTADO" NUMBER, 
	"ID_PAIS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_AGREGADORES"."ID" IS 'pk de la tabla SDA_AGREGADORES';
 
   COMMENT ON COLUMN "CRISTO"."SDA_AGREGADORES"."NOMBRE_AGREGADOR" IS 'El nombre del agregador';
 
   COMMENT ON COLUMN "CRISTO"."SDA_AGREGADORES"."ESTADO" IS 'El estado del agregador';
 
   COMMENT ON COLUMN "CRISTO"."SDA_AGREGADORES"."ID_PAIS" IS 'fk con la tabla paises del agregador';
--------------------------------------------------------
--  DDL for Table SDA_LOG_DEPURACION
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_LOG_DEPURACION" 
   (	"ID" NUMBER, 
	"SUSCRIPTOR" VARCHAR2(50 BYTE), 
	"RESPUESTA" VARCHAR2(4000 BYTE), 
	"ENVIO" VARCHAR2(4000 BYTE), 
	"ESTADO_TRANSACCION" VARCHAR2(255 BYTE), 
	"FECHA_TRANSACCION" TIMESTAMP (6), 
	"TIPO_TRANSACCION" VARCHAR2(50 BYTE), 
	"ID_METODO" NUMBER, 
	"ID_USUARIO_SISTEMA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."ID" IS 'pk de la tabla de SDA_LOG_DEPURACION';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."SUSCRIPTOR" IS 'numero de telefono que se desea depurar';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."RESPUESTA" IS 'respuesta obtenida al invocar al metodo web del servicio de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."ENVIO" IS 'archivo enviado al servicio de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."ESTADO_TRANSACCION" IS 'estado de la depuracion la cual sera mostrada en el reporte';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."FECHA_TRANSACCION" IS 'Fecha en la que fue ejecutado la depuracion';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."TIPO_TRANSACCION" IS 'Tipo de depuracion ARCHIVO MASIVA UNITARIA';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."ID_METODO" IS 'FK con la tabla de SDA_METODOS';
 
   COMMENT ON COLUMN "CRISTO"."SDA_LOG_DEPURACION"."ID_USUARIO_SISTEMA" IS 'FK con la tabla de SDA_USUARIO_SISTEMA';
--------------------------------------------------------
--  DDL for Table SDA_METODOS
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_METODOS" 
   (	"ID" NUMBER, 
	"ID_AGREGADOR" NUMBER, 
	"ESTADO" NUMBER, 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"USUARIO" VARCHAR2(255 BYTE), 
	"CONTRASENIA" VARCHAR2(255 BYTE), 
	"END_POINT" VARCHAR2(1000 BYTE), 
	"SEGURIDAD" NUMBER, 
	"ORDEN_EJECUCION" NUMBER, 
	"INPUTMESSAGETEXT" VARCHAR2(4000 BYTE), 
	"INPUTMESSAGENAME" VARCHAR2(255 BYTE), 
	"SERVICE_NAME" VARCHAR2(20 BYTE), 
	"SOAPACTIONURI" VARCHAR2(255 BYTE), 
	"NAMESPACEURI" VARCHAR2(255 BYTE), 
	"STYLE" VARCHAR2(255 BYTE), 
	"TARGETMETHODNAME" VARCHAR2(255 BYTE), 
	"TARGETOBJECTURI" VARCHAR2(255 BYTE), 
	"TARGETURL" VARCHAR2(255 BYTE), 
	"WSDL_AGREGADOR" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."ID" IS 'pk de la tabla metodos de los servicios web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."ID_AGREGADOR" IS 'fk relacion con la tabla de agregadores de los servicios web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."ESTADO" IS 'estado del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."NOMBRE" IS 'nombre del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."USUARIO" IS 'USUARIO del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."CONTRASENIA" IS 'CONTRASENIA del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."END_POINT" IS 'END_POINT del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."SEGURIDAD" IS 'SEGURIDAD significa si saldra por el puerto de http o por el puerto del https el metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."ORDEN_EJECUCION" IS 'ORDEN_EJECUCION del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."INPUTMESSAGETEXT" IS 'el cuerpo del mensaje del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."INPUTMESSAGENAME" IS 'el nombre del mensaje de envio del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."SERVICE_NAME" IS 'nombre del servicioque contiene el metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."SOAPACTIONURI" IS 'SOAPACTIONURI dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."NAMESPACEURI" IS 'NAMESPACEURI dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."STYLE" IS 'STYLE dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."TARGETMETHODNAME" IS 'TARGETMETHODNAME dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."TARGETOBJECTURI" IS 'TARGETOBJECTURI dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."TARGETURL" IS 'TARGETURL dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_METODOS"."WSDL_AGREGADOR" IS 'WSDL_AGREGADOR dato requerido para el parseo automatico del metodo del servicio web de los agregadores';
--------------------------------------------------------
--  DDL for Table SDA_PAISES
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_PAISES" 
   (	"ID" NUMBER, 
	"PAIS" VARCHAR2(100 BYTE), 
	"CODIGO" VARCHAR2(10 BYTE), 
	"STATUS" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_PAISES"."ID" IS 'pk de la tabla SDA_PAISES de donde sera ejecutado el agregador';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PAISES"."PAIS" IS 'El nombre del pais de donde sera ejecutado en agregador';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PAISES"."CODIGO" IS 'El codigo de pais de donde sera ejecutado en agregador';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PAISES"."STATUS" IS 'El estado del pais de donde sera ejecutado en agregador';
--------------------------------------------------------
--  DDL for Table SDA_PARAMETROS
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_PARAMETROS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"ID_METODO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS"."ID" IS 'pk de la tabla de SDA_PARAMETROS';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS"."NOMBRE" IS 'nombre del parametro a enviar en el servicio web de los agregadores';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS"."ID_METODO" IS 'fk con la tabla de metodos';
--------------------------------------------------------
--  DDL for Table SDA_PARAMETROS_SISTEMA
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" 
   (	"ID" NUMBER, 
	"KEY" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS_SISTEMA"."ID" IS 'pk de la tabla de SDA_PARAMETROS_SISTEMA';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS_SISTEMA"."KEY" IS 'nombre del parametro que sera utilizado dentro del sistema';
 
   COMMENT ON COLUMN "CRISTO"."SDA_PARAMETROS_SISTEMA"."VALUE" IS 'valor del parametro que sera utilizado dentro del sistema';
--------------------------------------------------------
--  DDL for Table SDA_RESPUESTAS
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_RESPUESTAS" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"ID_METODO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_RESPUESTAS"."ID" IS 'pk de la tabla de SDA_RESPUESTAS';
 
   COMMENT ON COLUMN "CRISTO"."SDA_RESPUESTAS"."NOMBRE" IS 'nombre del parametro a recibir el servicio web de los agregadores cada uno de estos sera guardado en la tabla de logs';
 
   COMMENT ON COLUMN "CRISTO"."SDA_RESPUESTAS"."ID_METODO" IS 'fk con la tabla de metodos';
--------------------------------------------------------
--  DDL for Table SDA_USUARIO_SISTEMA
--------------------------------------------------------

  CREATE TABLE "CRISTO"."SDA_USUARIO_SISTEMA" 
   (	"ID" NUMBER, 
	"USUARIO" VARCHAR2(255 BYTE), 
	"CONTRASENIA" VARCHAR2(255 BYTE), 
	"ESTADO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "CRISTO"."SDA_USUARIO_SISTEMA"."ID" IS 'pk de la tabla de SDA_USUARIO_SISTEMA';
 
   COMMENT ON COLUMN "CRISTO"."SDA_USUARIO_SISTEMA"."USUARIO" IS 'nombre del usuario con permisos de entrar al sistema';
 
   COMMENT ON COLUMN "CRISTO"."SDA_USUARIO_SISTEMA"."CONTRASENIA" IS 'contrasenia del usuario con permisos de entrar al sistema';
 
   COMMENT ON COLUMN "CRISTO"."SDA_USUARIO_SISTEMA"."ESTADO" IS 'estado del usuario con permisos de entrar al sistema';
REM INSERTING into CRISTO.CLIENTE_TEL
SET DEFINE OFF;
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (1,'50370001635');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (2,'50370001639');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (3,'50370001647');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (4,'50370001650');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (5,'50370001659');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (6,'50370001660');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (7,'50255846245');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (8,'50247166159');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (9,'50242155220');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (10,'50242435799');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (11,'50242107214');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (12,'50247009375');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (13,'50370001661');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (14,'50370001665');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (15,'50370001671');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (16,'50370001678');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (17,'50370001679');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (18,'50370001682');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (19,'50370001690');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (20,'50370001701');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (21,'50370001708');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (22,'50370001712');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (23,'50370001720');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (24,'50370001730');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (25,'50370001742');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (26,'50370001748');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (27,'50370001761');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (28,'50370001762');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (29,'50370001764');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (30,'50370001770');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (31,'50370001773');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (32,'50370001777');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (33,'50370001784');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (34,'50370001787');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (35,'50370001788');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (36,'50370001790');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (37,'50370001795');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (38,'50370001837');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (39,'50370001839');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (40,'50370001841');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (41,'50370001844');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (42,'50370001864');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (43,'50370001865');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (44,'50370001868');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (45,'50370001872');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (47,'50370001875');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (48,'50370001877');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (49,'50370001878');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (50,'50370001882');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (51,'50370001883');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (52,'50370001884');
Insert into CRISTO.CLIENTE_TEL (ID,NUMERO) values (53,'50370001887');
REM INSERTING into CRISTO.HABITANTES
SET DEFINE OFF;
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000001','Patricia','Sanchez','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000002','Isabel','Reyes','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000003','Deysi','siliezar','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000004','Angela','Ruano','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000005','Margarita','Alvarado','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000006','Claudia','Siliezar','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000007','Lucia','Palacios','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000008','Matilde','Cubias','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000009','Anotonio','Alfaro','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000010','Maria','Chicas','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000011','Juana','Hernandez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000012','Yolanda','Hernandez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000013','Norma','Hernandez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000014','Roman','Hernandez','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000015','Claudia','Hernandez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000016','Victor','Lira','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000017','Ana','Ramirez','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000018','julio','Iraheta','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000019','Elmer','Alas','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000020','Marta','Martinez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000021','Laura Duran','Duran','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000022','Douglas','Mejia','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000023','Edwin','Mejia','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000024','Grupo','24 de Septiembre','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000025','Ernesto','Sanchez','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000026','Orlando','Bonilla','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000027','Demetrio','Lopez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000028','Gloria','Perez','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000029','Veronica','Estrada','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000030','Santana','Reyes','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000031','Eliza','Hernandez','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000032','Julia','Monterroza','H');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000033','Marlo','Monterroza','D');
Insert into CRISTO.HABITANTES (HABITANTES_ID,NOMBRES,APELLIDOS,CARGO) values ('00000034','Guadalupe','Vega','H');
REM INSERTING into CRISTO.SDA_AGREGADORES
SET DEFINE OFF;
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (1,'MOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (2,'CONTENTAMOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (3,'TELEVIDA',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (4,'P MOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (5,'WIRELES IDEA',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (6,'WAU',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (7,'TECH4MOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (8,'ESTRATEGIAS MOVILES',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (9,'ZED',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (10,'BINBIT',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (11,'TIMWE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (12,'OPRATEL',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (13,'MOVIXLA',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (14,'GRUPO M',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (15,'XURPAS',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (16,'SMS AMERICAS',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (17,'WORLD2 MOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (18,'INTERACEL',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (19,'CRONOS',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (20,'PINGSA',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (21,'NUESTRO DIARIO',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (22,'BIZNET (CELUMANIX)',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (23,'VAS LATIN',1,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (24,'NEOMOBILE',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (25,'NARANYA',0,1);
Insert into CRISTO.SDA_AGREGADORES (ID,NOMBRE_AGREGADOR,ESTADO,ID_PAIS) values (26,'SMT',1,1);
REM INSERTING into CRISTO.SDA_LOG_DEPURACION
SET DEFINE OFF;
Insert into CRISTO.SDA_LOG_DEPURACION (ID,SUSCRIPTOR,RESPUESTA,ENVIO,ESTADO_TRANSACCION,FECHA_TRANSACCION,TIPO_TRANSACCION,ID_METODO,ID_USUARIO_SISTEMA) values (1,'50258260744','4','<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:loc="http://www.csapi.org/schema/parlayx/blackgray/v1_0/local"><soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>PA00000737</wsse:Username><wsse:Password Type="...#PasswordDigest">tyNa/iAsO90cUk+oSeaDlR1qww8=</wsse:Password><wsse:Nonce>f2366437-e3bf-49b0-9839-97b11be66da3</wsse:Nonce><wsse:Created>2014-09-24T08:01:22Z</wsse:Created></wsse:UsernameToken></wsse:Security><tns:RequestSOAPHeader xmlns:tns="http://www.huawei.com.cn/schema/common/v2_1"><tns:AppId>35000001000001</tns:AppId><tns:TransId>2014011716010012345</tns:TransId><tns:OA>50258260744</tns:OA><tns:FA>50258260744</tns:FA></tns:RequestSOAPHeader></soapenv:Header><soapenv:Body><loc:deleteGrayList><loc:version>_*version_*</loc:version><loc:grayList><grayee><msisdn>50258260744</msisdn>    </grayee></loc:grayList></loc:deleteGrayList></soapenv:Body></soapenv:Envelope>','Exitosa',to_timestamp('24/09/14 08:01:25.125000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'UNITARIA',1,1);
Insert into CRISTO.SDA_LOG_DEPURACION (ID,SUSCRIPTOR,RESPUESTA,ENVIO,ESTADO_TRANSACCION,FECHA_TRANSACCION,TIPO_TRANSACCION,ID_METODO,ID_USUARIO_SISTEMA) values (2,'50258260744','9','<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:loc="http://www.csapi.org/schema/parlayx/blackgray/v1_0/local"><soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>PA00000737</wsse:Username><wsse:Password Type="...#PasswordDigest">tyNa/iAsO90cUk+oSeaDlR1qww8=</wsse:Password><wsse:Nonce>f2366437-e3bf-49b0-9839-97b11be66da3</wsse:Nonce><wsse:Created>2014-09-24T08:01:22Z</wsse:Created></wsse:UsernameToken></wsse:Security><tns:RequestSOAPHeader xmlns:tns="http://www.huawei.com.cn/schema/common/v2_1"><tns:AppId>35000001000001</tns:AppId><tns:TransId>2014011716010012345</tns:TransId><tns:OA>50258260744</tns:OA><tns:FA>50258260744</tns:FA></tns:RequestSOAPHeader></soapenv:Header><soapenv:Body><loc:deleteGrayList><loc:version>_*version_*</loc:version><loc:grayList><grayee><msisdn>50258260744</msisdn>    </grayee></loc:grayList></loc:deleteGrayList></soapenv:Body></soapenv:Envelope>','Exitosa',to_timestamp('24/09/14 08:01:25.381000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),'UNITARIA',1,1);
REM INSERTING into CRISTO.SDA_METODOS
SET DEFINE OFF;
Insert into CRISTO.SDA_METODOS (ID,ID_AGREGADOR,ESTADO,NOMBRE,USUARIO,CONTRASENIA,END_POINT,SEGURIDAD,ORDEN_EJECUCION,INPUTMESSAGETEXT,INPUTMESSAGENAME,SERVICE_NAME,SOAPACTIONURI,NAMESPACEURI,STYLE,TARGETMETHODNAME,TARGETOBJECTURI,TARGETURL,WSDL_AGREGADOR) values (1,26,1,'deleteGrayList','PA00000737','Admin111','https://hub.americamovil.com/sag/services/blackgrayService',1,1,'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:loc="http://www.csapi.org/schema/parlayx/blackgray/v1_0/local"><soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>_*user_*</wsse:Username><wsse:Password Type="...#PasswordDigest">_*passSMT_*</wsse:Password><wsse:Nonce>_*nonce_*</wsse:Nonce><wsse:Created>_*dateSMT_*</wsse:Created></wsse:UsernameToken></wsse:Security><tns:RequestSOAPHeader xmlns:tns="http://www.huawei.com.cn/schema/common/v2_1"><tns:AppId>35000001000001</tns:AppId><tns:TransId>2014011716010012345</tns:TransId><tns:OA>_*movil_*</tns:OA><tns:FA>_*movil_*</tns:FA></tns:RequestSOAPHeader></soapenv:Header><soapenv:Body><loc:deleteGrayList><loc:version>_*version_*</loc:version><loc:grayList><grayee><msisdn>_*movil_*</msisdn>    </grayee></loc:grayList></loc:deleteGrayList></soapenv:Body></soapenv:Envelope>',null,null,'loc:deleteGrayList',null,null,null,null,null,null);
REM INSERTING into CRISTO.SDA_PAISES
SET DEFINE OFF;
Insert into CRISTO.SDA_PAISES (ID,PAIS,CODIGO,STATUS) values (3,'HONDURAS','504',1);
Insert into CRISTO.SDA_PAISES (ID,PAIS,CODIGO,STATUS) values (4,'NICARAGUA','505',1);
Insert into CRISTO.SDA_PAISES (ID,PAIS,CODIGO,STATUS) values (1,'GUATEMALA','502',1);
Insert into CRISTO.SDA_PAISES (ID,PAIS,CODIGO,STATUS) values (2,'EL SALVADOR','503',1);
Insert into CRISTO.SDA_PAISES (ID,PAIS,CODIGO,STATUS) values (5,'COSTA RICA','506',1);
REM INSERTING into CRISTO.SDA_PARAMETROS
SET DEFINE OFF;
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (1,'user',1);
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (2,'passSMT',1);
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (3,'nonce',1);
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (4,'dateSMT',1);
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (5,'movil',1);
Insert into CRISTO.SDA_PARAMETROS (ID,NOMBRE,ID_METODO) values (6,'movil',1);
REM INSERTING into CRISTO.SDA_PARAMETROS_SISTEMA
SET DEFINE OFF;
REM INSERTING into CRISTO.SDA_RESPUESTAS
SET DEFINE OFF;
Insert into CRISTO.SDA_RESPUESTAS (ID,NOMBRE,ID_METODO) values (1,'ns1:resultCode',1);
Insert into CRISTO.SDA_RESPUESTAS (ID,NOMBRE,ID_METODO) values (2,'errorCode',1);
REM INSERTING into CRISTO.SDA_USUARIO_SISTEMA
SET DEFINE OFF;
Insert into CRISTO.SDA_USUARIO_SISTEMA (ID,USUARIO,CONTRASENIA,ESTADO) values (1,'admin','admin',1);
--------------------------------------------------------
--  DDL for Index CLIENTE_TEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."CLIENTE_TEL_PK" ON "CRISTO"."CLIENTE_TEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HABITANTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."HABITANTES_PK" ON "CRISTO"."HABITANTES" ("HABITANTES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_AGREGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_AGREGADORES_PK" ON "CRISTO"."SDA_AGREGADORES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_LOG_DEPURACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_LOG_DEPURACION_PK" ON "CRISTO"."SDA_LOG_DEPURACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_METODOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_METODOS_PK" ON "CRISTO"."SDA_METODOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_PAISES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_PAISES_PK" ON "CRISTO"."SDA_PAISES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_PARAMETROS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_PARAMETROS_PK" ON "CRISTO"."SDA_PARAMETROS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_PARAMETROS_SISTEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_PARAMETROS_SISTEMA_PK" ON "CRISTO"."SDA_PARAMETROS_SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_RESPUESTA_PK" ON "CRISTO"."SDA_RESPUESTAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SDA_USUARIO_SISTEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTO"."SDA_USUARIO_SISTEMA_PK" ON "CRISTO"."SDA_USUARIO_SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE_TEL
--------------------------------------------------------

  ALTER TABLE "CRISTO"."CLIENTE_TEL" ADD CONSTRAINT "CLIENTE_TEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."CLIENTE_TEL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HABITANTES
--------------------------------------------------------

  ALTER TABLE "CRISTO"."HABITANTES" ADD CONSTRAINT "HABITANTES_PK" PRIMARY KEY ("HABITANTES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."HABITANTES" MODIFY ("HABITANTES_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."HABITANTES" MODIFY ("NOMBRES" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."HABITANTES" MODIFY ("APELLIDOS" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."HABITANTES" MODIFY ("CARGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_AGREGADORES
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_AGREGADORES" ADD CONSTRAINT "SDA_AGREGADORES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_AGREGADORES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_AGREGADORES" MODIFY ("NOMBRE_AGREGADOR" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_AGREGADORES" MODIFY ("ID_PAIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_LOG_DEPURACION
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" ADD CONSTRAINT "SDA_LOG_DEPURACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("SUSCRIPTOR" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("ESTADO_TRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("FECHA_TRANSACCION" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("ID_METODO" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" MODIFY ("ID_USUARIO_SISTEMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_METODOS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_METODOS" ADD CONSTRAINT "SDA_METODOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("ID_AGREGADOR" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("END_POINT" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("INPUTMESSAGETEXT" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_METODOS" MODIFY ("ORDEN_EJECUCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_PAISES
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_PAISES" ADD CONSTRAINT "SDA_PAISES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_PAISES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_PAISES" MODIFY ("PAIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_PARAMETROS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_PARAMETROS" ADD CONSTRAINT "SDA_PARAMETROS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS" MODIFY ("ID_METODO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_PARAMETROS_SISTEMA
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" ADD CONSTRAINT "SDA_PARAMETROS_SISTEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" MODIFY ("KEY" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_PARAMETROS_SISTEMA" MODIFY ("VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_RESPUESTAS" ADD CONSTRAINT "SDA_RESPUESTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_RESPUESTAS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_RESPUESTAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_RESPUESTAS" MODIFY ("ID_METODO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SDA_USUARIO_SISTEMA
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_USUARIO_SISTEMA" ADD CONSTRAINT "SDA_USUARIO_SISTEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_USUARIO_SISTEMA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_USUARIO_SISTEMA" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_USUARIO_SISTEMA" MODIFY ("CONTRASENIA" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTO"."SDA_USUARIO_SISTEMA" MODIFY ("ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SDA_AGREGADORES
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_AGREGADORES" ADD CONSTRAINT "SDA_AGREGADORES_PAISES_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "CRISTO"."SDA_PAISES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SDA_LOG_DEPURACION
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" ADD CONSTRAINT "SDA_LOG_DEPURACION_METODOS_FK" FOREIGN KEY ("ID_METODO")
	  REFERENCES "CRISTO"."SDA_METODOS" ("ID") ENABLE;
 
  ALTER TABLE "CRISTO"."SDA_LOG_DEPURACION" ADD CONSTRAINT "SDA_LOG_USUARIO_FK" FOREIGN KEY ("ID_USUARIO_SISTEMA")
	  REFERENCES "CRISTO"."SDA_USUARIO_SISTEMA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SDA_METODOS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_METODOS" ADD CONSTRAINT "SDA_METODOS_AGREGADORES_FK" FOREIGN KEY ("ID_AGREGADOR")
	  REFERENCES "CRISTO"."SDA_AGREGADORES" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SDA_PARAMETROS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_PARAMETROS" ADD CONSTRAINT "SDA_PARAMETROS_METODOS_FK" FOREIGN KEY ("ID_METODO")
	  REFERENCES "CRISTO"."SDA_METODOS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SDA_RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "CRISTO"."SDA_RESPUESTAS" ADD CONSTRAINT "SDA_RESPUESTAS_METODOS_FK" FOREIGN KEY ("ID_METODO")
	  REFERENCES "CRISTO"."SDA_METODOS" ("ID") ON DELETE CASCADE ENABLE;
